-- Ejecuta este SQL en Supabase > SQL Editor.
create table if not exists public.devices (
  device_id text primary key,
  name text not null default 'Lámpara ESP32',
  lamp_on boolean not null default false,
  brightness integer not null default 0 check (brightness between 0 and 100),
  temperature numeric,
  voltage numeric,
  current numeric,
  power numeric,
  last_seen timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.telemetry (
  id bigint generated by default as identity primary key,
  device_id text not null references public.devices(device_id) on delete cascade,
  temperature numeric,
  voltage numeric,
  current numeric,
  power numeric,
  brightness integer check (brightness between 0 and 100),
  lamp_on boolean,
  created_at timestamptz not null default now()
);

create table if not exists public.commands (
  id bigint generated by default as identity primary key,
  device_id text not null references public.devices(device_id) on delete cascade,
  type text not null check (type in ('power','brightness')),
  value jsonb not null,
  created_at timestamptz not null default now(),
  executed_at timestamptz
);

insert into public.devices(device_id,name)
values ('lampara-01','Lámpara ESP32')
on conflict (device_id) do nothing;

alter table public.devices enable row level security;
alter table public.telemetry enable row level security;
alter table public.commands enable row level security;

-- DEMO: dashboard público. Para producción, cambia estas políticas por Auth.
create policy "dashboard read devices" on public.devices for select using (true);
create policy "dashboard read telemetry" on public.telemetry for select using (true);
create policy "dashboard insert commands" on public.commands for insert with check (true);

-- IMPORTANTE:
-- El ESP32 NO debería usar la anon key para operaciones privilegiadas.
-- Lo ideal es que el ESP32 escriba mediante un endpoint seguro (Edge Function)
-- o un backend intermedio con autenticación propia.
-- Habilita Realtime para devices y telemetry desde Database > Replication.
